# Generated by Django 2.2.3 on 2019-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('process', models.CharField(default='', max_length=200)),
                ('local_ip', models.CharField(default='', max_length=200)),
                ('local_port', models.CharField(default='', max_length=200)),
                ('remote_ip', models.CharField(default='', max_length=200)),
                ('remote_port', models.CharField(default='', max_length=200)),
                ('protocol', models.CharField(default='', max_length=200)),
                ('direction', models.CharField(default='', max_length=200)),
                ('action', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('enalbled', models.CharField(default='', max_length=200)),
                ('profile', models.CharField(default='', max_length=400)),
                ('redirect_ip', models.CharField(default='', max_length=40)),
                ('redirect_port', models.CharField(default='', max_length=40)),
                ('content_all1', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='序号')),
                ('name', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='内容')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '规则',
                'db_table': 'tb_Rule',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('level', models.CharField(default='', max_length=10)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='var',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
