# Generated by Django 2.2.3 on 2019-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='id_f',
            field=models.CharField(default='', max_length=128),
        ),
    ]
