# Generated by Django 2.2.3 on 2019-07-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
