# Generated by Django 2.2.3 on 2019-08-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0004_log_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=128),
        ),
    ]
