# Generated by Django 2.2.3 on 2019-07-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0004_firewall'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='action',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='direction',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='enalbled',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='local_ip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='local_port',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='process',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='profile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='protocol',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='remote_ip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='remote_port',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firewall',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
